name: mobile_skeleton
description: A starting point for develop flutter application

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #view
  cupertino_icons: ^0.1.3
  feather_icons_flutter: 4.7.4
  fluttertoast: ^7.0.4
  flutter_svg: ^0.19.0
  intl: ^0.16.1
  url_launcher: ^5.7.10
  flutter_local_notifications: ^3.0.1+6

  #networking
  dio: ^3.0.8
  shared_preferences: ^0.5.5
  json_annotation: ^3.0.1
  equatable: ^1.0.0
  rxdart: ^0.23.1
  get_it: ^3.0.3
  http: any
  ftpconnect: ^0.2.1
  firebase_core: ^0.5.2
  firebase_messaging: ^7.0.3
  firebase_auth: ^0.18.3+1
  firebase_analytics: ^6.3.0
  connectivity: ^2.0.2

  #architecture
  flutter_bloc: ^3.1.0

  #sqlite
  sqfentity: ^1.4.0+3
  sqfentity_gen: ^1.4.0+2
  path_provider: any

  logger: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^3.2.3
  build_runner: ^1.7.2
  test_coverage: ^0.4.0
  bloc_test: ^3.0.0
  mockito: ^4.1.1
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dummy_launcher.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/nunito-sans/NunitoSans-Regular.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-Bold.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-SemiBold.ttf
        - asset: assets/fonts/nunito-sans/NunitoSans-ExtraBold.ttf
    - family: NotoSerifKR
      fonts:
        - asset: assets/fonts/noto-serif/NotoSerifKR-Regular.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-Bold.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-Black.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-Light.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-ExtraLight.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-Medium.otf
        - asset: assets/fonts/noto-serif/NotoSerifKR-SemiBold.otf
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
